name: webviewmeet_fluttertemplate
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # 添加依赖适配屏幕
  flutter_screenutil: 5.9.3
  #添加依赖
  fluttertoast: 8.2.10
  #添加获取设备信息的依赖
  device_info_plus: 9.1.2
  #webviewflutter
  webview_flutter: 4.10.0
  webview_flutter_android: any
  webview_flutter_wkwebview: any
#  flutter_inappwebview: 5.7.2+3
#  url_launcher: any
  #http
  http: 1.2.2
  shared_preferences: 2.3.4
  get_ip_address: 0.0.7
  #  get_ip: any
  #屏幕常亮
  wakelock_plus: 1.2.10
  #调节系统音量
  flutter_volume_controller: 1.3.3
#  volume_controller: 2.0.8
  #  截取屏幕
  screenshot: 3.0.0
  flutter_image_compress: any
  flutter_downloader: any
  path_provider: 2.1.5
  archive: 4.0.2 #解/压缩
  flutter_archive: 5.0.0 #解/压缩
  permission_handler: 11.3.1
  progress_dialog_null_safe: 3.0.0
  toast: 0.3.0
  #websocket
  web_socket_channel: 3.0.1
  #dio
  dio: 5.7.0
  #sqflite
  sqflite: 2.4.1
  #  获取内存
  system_info2: 3.0.2
  #  获取当前存储空间
  disk_space_update: 0.0.2
  #添加mqtt的依赖
  mqtt_client: 10.5.1
  #  文件加密解密
  aes_crypt_null_safe: 3.0.0
  flutter_local_notifications: 18.0.1
  #  监听屏幕有无打开
  screen_state: 4.0.0
  flutter_background_service: 5.1.0
  #  音频播放
  just_audio: 0.9.42
#  audioplayers: any
  #  mqtt加解密
  encrypt: 5.0.3
  external_path: 1.0.3
  restart_app: 1.2.0
  #  生成二维码
  qr_flutter: any
  ntp: any
  uuid: 4.5.1
  package_info_plus: ^8.1.2
  intl: any
  camera: ^0.10.6
  image_picker: ^1.1.2
  image: any
  google_mlkit_face_detection:
    path: google_mlkit_face_detection

dependency_overrides:
  google_mlkit_commons:
    path: google_mlkit_commons

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - images/
    - files/
